USE wordy;
DROP table IF EXISTS books;

CREATE TABLE IF NOT EXISTS books (
    id INT(6) NOT NULL AUTO_INCREMENT,
    title VARCHAR(120) DEFAULT 'unknown',
    sentence TEXT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
)
